import Head from 'next/head'
import React from "react";
import styles from '@/styles/AboutInfo.module.scss'
import NavSection from "@/components/NavBar/NavSection";

export default function Payment() {

    return (
        <>
            <Head>
                <title>Оплата и доставка</title>
                <meta name="description" content="Generated by create next app"/>
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
                />
                <link rel="icon" href="/sneaker_svg.svg"/>
            </Head>
            <div className={styles.mainContent}>
                <NavSection pages={[{link: '/', name: 'Главная'}, {link: '/about', name: 'Информация'}]}/>
                <div className={styles.textContent}>
                    <div>
                        <h1>Процесс покупки</h1>
                        <p>Выбираете понравившийся товар.</p>
                        <p>Присылаете актикул(или ссылку) и размер в мессенджере.</p>
                        <p>После подтверждения наличия товара указываете адрес транспортной компании, где удобно забрать
                            покупку, и оплачиваете.</p>
                        <p>При отправке товара мы пришлем Вам трекинг-номер для отслеживания.</p>
                    </div>
                    <div>
                        <h1>Оплата</h1>
                        <p>Оплату заказа в Интернет-магазине принимаем переводом или Системой Быстрых Платежей.</p>
                    </div>
                    <div>
                        <h1>Доставка</h1>
                        <h2>СДЭК</h2>
                        <p>Срок доставки ориентировочно 2-5 рабочих дней с момента отправления заказа (срок отправки
                            заказа
                            1-2 дня, не считая дня поступления заказа).</p>
                        <p>Стоимость доставки ≈ 500 рублей.</p>
                        <p>Доставка по указанному адресу ТК.</p>
                        <p>Возможность отслеживания посылки по трекинг-номеру.</p>
                        <p>В случае не подошедшего товара, отправьте нам его обратно отдельной посылкой, заполнив и
                            вложив <span>бланк возврата</span>.</p>
                    </div>
                    <div>
                        <h1>Отследить товар</h1>
                        <p>При отправке товара мы предоставляем Вам трекинг-номер транспортной компании.</p>
                        <p>На сайте ТК можно отслеживать местоположение товара.</p>
                    </div>
                </div>
            </div>
        </>
    )
}