import Head from 'next/head'
import React from "react";
import styles from '@/styles/About.module.scss'
import Link from "next/link";

export default function About() {

    return (
        <>
            <Head>
                <title>Информация</title>
                <meta name="description" content="Generated by create next app"/>
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
                />
                <link rel="icon" href="/sneaker_svg.svg"/>
            </Head>
            <div className={styles.mainContent}>
                <div className={styles.blockInfo}>
                    <Link
                        href={`/about/payment`}
                        className={styles.blockInfoElem}
                    >
                        <div>
                            <span>Оплата и доставка</span>
                        </div>
                        <p>Информация о способах оплаты и условиях доставки товаров.</p>
                    </Link>
                    <Link
                        href={`/about/refund`}
                        className={styles.blockInfoElem}
                    >
                        <div>
                            <span>Возврат</span>
                        </div>
                        <p>Правила и процедура возврата товара, включая сроки и условия.</p>
                    </Link>
                    <Link
                        href={`/about/product`}
                        className={styles.blockInfoElem}
                    >
                        <div>
                            <span>Товар</span>
                        </div>
                        <p>Руководство по выбору правильного размера, уход за товаром и другие вопросы.</p>
                    </Link>
                    <Link
                        href={`/about/policy`}
                        className={styles.blockInfoElem}
                    >
                        <div>
                            <span>Политика конфиденциальности</span>
                        </div>
                        <p>Описание основных принципов и ценностей компании, а также информация о защите данных и
                            конфиденциальности клиентов.</p>
                    </Link>
                </div>
            </div>
        </>
    )
}