import Head from 'next/head'
import React from "react";

export default function Home() {

    return (
        <>
            <Head>
                <title>Sneakers Vibe</title>
                <meta name="description" content="Generated by create next app"/>
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
                />
                <link rel="icon" href="/sneaker_svg.svg"/>
            </Head>
            <div>

            </div>
        </>
    )
}